# This is a configuration file template for the SCION beacon server.
# It is instantiated with concrete values in the BeaconServer class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[general]
ID = "beacon_server"
ReconnectToDispatcher = true
ConfigDir = "%s"

[metrics]
Prometheus = "[127.0.0.1]:32041"

[logging.file]
Path = "%s"
Level = "%s"
MaxAge = 3
MaxBackups = 1

[BS]
OriginationInterval = "5s"
PropagationInterval = "5s"
RevOverlap = "5s"
RevTTL = "20s"

[beaconDB]
Connection = "%s"

[trustDB]
Connection = "%s"