# This is a configuration file template for the SCION border router.
# It is instantiated with concrete values in the BorderRouter class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[general]
ID = "border_router"
ConfigDir = "%s"

[metrics]
Prometheus = "[127.0.0.1]:32045"

[logging.file]
Path = "%s"
Level = "%s"
MaxAge = 3
MaxBackups = 1

[br]
Profile = false