# This is a configuration file template for the SCION certificate server.
# It is instantiated with concrete values in the CertificateServer class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[general]
ID = "certificate_server"
ReconnectToDispatcher = true
ConfigDir = "%s"

[metrics]
Prometheus = "[127.0.0.1]:32042"

[logging.file]
Path = "%s"
Level = "%s"
MaxAge = 3
MaxBackups = 1

[trustDB]
Connection = "%s"

[sd_client]
Path = "%s"

[cs]
IssuerReissueTime = "3d"
LeafReissueTime = "6h"
ReissueRate = "10s"
ReissueTimeout = "5s"