# This is a configuration file template for the SCION daemon.
# It is instantiated with concrete values in the Daemon class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[general]
ID = "daemon"
ReconnectToDispatcher = true
ConfigDir = "%s"

[metrics]
Prometheus = "[127.0.0.1]:30455"

[logging.file]
Path = "%s"
Level = "%s"
MaxAge = 3
MaxBackups = 1

[sd]
Public = "%s"
SocketFileMode = "0777"
Reliable = "%s"
Unix = "%s"

[sd.PathDB]
Connection = "%s"

[trustDB]
Connection = "%s"