# This is a configuration file template for the SCION dispatcher.
# It is instantiated with concrete values in the Dispatcher class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[dispatcher]
id = "dispatcher"
socket_file_mode = "0777"
application_socket = "%s"

[metrics]
prometheus = "127.0.0.1:30441"

[log.file]
path = "%s"
level = "%s"
max_age = 3
max_backups = 1