# This is a configuration file template for the SCION path server.
# It is instantiated with concrete values in the PathServer class.
# The structure of this file depends on the SCION version and is thus linked to the binary located in jniLibs.

[general]
ID = "path_server"
ReconnectToDispatcher = true
ConfigDir = "%s"

[metrics]
Prometheus = "[127.0.0.1]:32043"

[logging.file]
Path = "%s"
Level = "%s"
MaxAge = 3
MaxBackups = 1

[trustDB]
Connection = "%s"

[ps.PathDB]
Connection = "%s"

[ps]
SegSync = true